# Example busybox container outputting custom logs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggers
  labels:
    app: custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      # Container named "example-logger" outputting date-related logs every 5 seconds
      - name: example-logger
        image: busybox
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 5; 
          echo `date '+%FT%T'` example stdout log; 
          echo `date '+%FT%T'` example stderr log 1>&2;
        done;"
        ]
      # Container named "yummy-logger" outputting hunger-inducing logs every 5 seconds
      - name: yummy-logger
        image: busybox
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 5; 
          echo `date '+%FT%T'` I like cookies and milk on Thursdays; 
          echo `date '+%FT%T'` But only if I have chocolate and bonbons on Fridays;
        done;"
        ]
      # Container named "random-logger" outputting logs every 5 seconds
      - name: random-logger
        image: chentex/random-logger
        imagePullPolicy: Always
